"""add_cost_tracking_tables

Revision ID: 429a30578e50
Revises: 0003_reconcile_points_balances
Create Date: 2025-12-18 22:45:12.419717

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '429a30578e50'
down_revision = '0003_reconcile_points_balances'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('input_price_per_1m', sa.Float(), nullable=False),
    sa.Column('output_price_per_1m', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=128), nullable=True),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_usage_job_id', 'token_usage', ['job_id'], unique=False)
    op.create_index('idx_token_usage_timestamp', 'token_usage', ['timestamp'], unique=False)
    op.create_index(op.f('ix_token_usage_job_id'), 'token_usage', ['job_id'], unique=False)
    op.create_index(op.f('ix_token_usage_model_id'), 'token_usage', ['model_id'], unique=False)
    op.create_index(op.f('ix_token_usage_timestamp'), 'token_usage', ['timestamp'], unique=False)
    op.drop_index(op.f('idx_gcs_uploads_expires'), table_name='gcs_uploads')
    op.create_index(op.f('ix_gcs_uploads_expires_at'), 'gcs_uploads', ['expires_at'], unique=False)
    op.create_index(op.f('ix_history_user_id'), 'history', ['user_id'], unique=False)
    op.drop_index(op.f('idx_oauth_states_expires'), table_name='oauth_states')
    op.create_index(op.f('ix_oauth_states_expires_at'), 'oauth_states', ['expires_at'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    
    # --- Data Seeding ---
    pricing_data = [
        # GPT-4o
        {
            "id": "gpt-4o",
            "input_price_per_1m": 5.00,
            "output_price_per_1m": 15.00,
            "currency": "USD",
            "active": True,
            "updated_at": 1734560000 
        },
        # GPT-4o-mini
        {
            "id": "gpt-4o-mini",
            "input_price_per_1m": 0.15,
            "output_price_per_1m": 0.60,
            "currency": "USD",
            "active": True,
            "updated_at": 1734560000
        },
        # GPT-5-mini (Estimated/Researched)
        {
            "id": "gpt-5-mini",
            "input_price_per_1m": 0.25,
            "output_price_per_1m": 2.00,
            "currency": "USD",
            "active": True,
            "updated_at": 1734560000
        },
    ]
    
    # Use the table object to enable bulk insert
    ai_models = sa.table('ai_models',
        sa.column('id', sa.String),
        sa.column('input_price_per_1m', sa.Float),
        sa.column('output_price_per_1m', sa.Float),
        sa.column('currency', sa.String),
        sa.column('active', sa.Boolean),
        sa.column('updated_at', sa.Integer)
    )
    
    op.bulk_insert(ai_models, pricing_data)
    # --- End Data Seeding ---

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_oauth_states_expires_at'), table_name='oauth_states')
    op.create_index(op.f('idx_oauth_states_expires'), 'oauth_states', ['expires_at'], unique=False)
    op.drop_index(op.f('ix_history_user_id'), table_name='history')
    op.drop_index(op.f('ix_gcs_uploads_expires_at'), table_name='gcs_uploads')
    op.create_index(op.f('idx_gcs_uploads_expires'), 'gcs_uploads', ['expires_at'], unique=False)
    op.drop_index(op.f('ix_token_usage_timestamp'), table_name='token_usage')
    op.drop_index(op.f('ix_token_usage_model_id'), table_name='token_usage')
    op.drop_index(op.f('ix_token_usage_job_id'), table_name='token_usage')
    op.drop_index('idx_token_usage_timestamp', table_name='token_usage')
    op.drop_index('idx_token_usage_job_id', table_name='token_usage')
    op.drop_table('token_usage')
    op.drop_table('ai_models')
    # ### end Alembic commands ###

