CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(64) PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    password_hash TEXT NULL,
    google_sub VARCHAR(255) NULL,
    created_at VARCHAR(64) NULL,
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT chk_users_provider CHECK (provider IN ('local','google'))
);

CREATE INDEX IF NOT EXISTS ix_users_email ON users (email);
CREATE INDEX IF NOT EXISTS ix_users_google_sub ON users (google_sub);

CREATE TABLE IF NOT EXISTS deleted_emails (
    email_hash VARCHAR(64) PRIMARY KEY,
    deleted_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
    token_hash VARCHAR(128) PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at INTEGER NOT NULL,
    expires_at INTEGER NOT NULL,
    user_agent TEXT NULL
);

CREATE INDEX IF NOT EXISTS ix_sessions_user_id ON sessions (user_id);
CREATE INDEX IF NOT EXISTS ix_sessions_expires_at ON sessions (expires_at);

CREATE TABLE IF NOT EXISTS history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts VARCHAR(64) NOT NULL,
    user_id VARCHAR(64) NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    email VARCHAR(255) NOT NULL,
    kind VARCHAR(64) NOT NULL,
    summary TEXT NOT NULL,
    data JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_history_user_ts ON history (user_id, ts);
CREATE INDEX IF NOT EXISTS ix_history_user_id ON history (user_id);

CREATE TABLE IF NOT EXISTS jobs (
    id VARCHAR(128) PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status VARCHAR(32) NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    progress INTEGER NOT NULL DEFAULT 0,
    message TEXT NULL,
    result_data JSONB NULL,
    CONSTRAINT chk_jobs_status CHECK (status IN ('pending','processing','completed','failed','cancelled'))
);

CREATE INDEX IF NOT EXISTS ix_jobs_user_id ON jobs (user_id);
CREATE INDEX IF NOT EXISTS idx_jobs_user_created_at ON jobs (user_id, created_at);

CREATE TABLE IF NOT EXISTS oauth_states (
    state VARCHAR(128) PRIMARY KEY,
    provider VARCHAR(32) NOT NULL,
    user_id VARCHAR(64) NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at INTEGER NOT NULL,
    expires_at INTEGER NOT NULL,
    user_agent TEXT NULL,
    ip VARCHAR(64) NULL
);

CREATE INDEX IF NOT EXISTS idx_oauth_states_provider ON oauth_states (provider);
CREATE INDEX IF NOT EXISTS ix_oauth_states_expires_at ON oauth_states (expires_at);

CREATE TABLE IF NOT EXISTS gcs_uploads (
    id VARCHAR(128) PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    object_name VARCHAR(1024) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    created_at INTEGER NOT NULL,
    expires_at INTEGER NOT NULL,
    used_at INTEGER NULL
);

CREATE INDEX IF NOT EXISTS ix_gcs_uploads_user_id ON gcs_uploads (user_id);
CREATE INDEX IF NOT EXISTS idx_gcs_uploads_user_created_at ON gcs_uploads (user_id, created_at);
CREATE INDEX IF NOT EXISTS ix_gcs_uploads_expires_at ON gcs_uploads (expires_at);

CREATE TABLE IF NOT EXISTS user_points (
    user_id VARCHAR(64) PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    balance INTEGER NOT NULL DEFAULT 1000,
    updated_at INTEGER NOT NULL,
    CONSTRAINT chk_user_points_balance_nonnegative CHECK (balance >= 0)
);

CREATE TABLE IF NOT EXISTS point_transactions (
    id VARCHAR(32) PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    delta INTEGER NOT NULL,
    reason VARCHAR(64) NOT NULL,
    meta JSONB NULL,
    created_at INTEGER NOT NULL,
    CONSTRAINT chk_point_transactions_delta_nonzero CHECK (delta <> 0)
);

CREATE INDEX IF NOT EXISTS ix_point_transactions_user_id ON point_transactions (user_id);
CREATE INDEX IF NOT EXISTS idx_point_transactions_user_created_at ON point_transactions (user_id, created_at);

CREATE TABLE IF NOT EXISTS ai_models (
    id VARCHAR(64) PRIMARY KEY,
    input_price_per_1m DOUBLE PRECISION NOT NULL,
    output_price_per_1m DOUBLE PRECISION NOT NULL,
    currency VARCHAR(3) NOT NULL,
    active BOOLEAN NOT NULL,
    updated_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS token_usage (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id VARCHAR(128) NULL REFERENCES jobs (id) ON DELETE SET NULL,
    model_id VARCHAR(64) NOT NULL REFERENCES ai_models (id),
    prompt_tokens INTEGER NOT NULL,
    completion_tokens INTEGER NOT NULL,
    total_tokens INTEGER NOT NULL,
    cost DOUBLE PRECISION NOT NULL,
    timestamp INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_token_usage_job_id ON token_usage (job_id);
CREATE INDEX IF NOT EXISTS idx_token_usage_timestamp ON token_usage (timestamp);
CREATE INDEX IF NOT EXISTS ix_token_usage_job_id ON token_usage (job_id);
CREATE INDEX IF NOT EXISTS ix_token_usage_model_id ON token_usage (model_id);
CREATE INDEX IF NOT EXISTS ix_token_usage_timestamp ON token_usage (timestamp);

CREATE TABLE IF NOT EXISTS usage_ledger (
    id VARCHAR(32) PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    job_id VARCHAR(128) NULL REFERENCES jobs (id) ON DELETE SET NULL,
    action VARCHAR(64) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    endpoint VARCHAR(255) NULL,
    model VARCHAR(64) NULL,
    tier VARCHAR(16) NULL,
    units JSONB NULL,
    cost_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
    credits_reserved INTEGER NOT NULL DEFAULT 0,
    credits_charged INTEGER NOT NULL DEFAULT 0,
    min_credits INTEGER NOT NULL DEFAULT 0,
    currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    status VARCHAR(32) NOT NULL,
    error TEXT NULL,
    idempotency_key VARCHAR(64) NULL UNIQUE,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_usage_ledger_user_created ON usage_ledger (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_usage_ledger_action ON usage_ledger (action);
CREATE INDEX IF NOT EXISTS idx_usage_ledger_status ON usage_ledger (status);
CREATE INDEX IF NOT EXISTS ix_usage_ledger_idempotency_key ON usage_ledger (idempotency_key);
CREATE INDEX IF NOT EXISTS ix_usage_ledger_job_id ON usage_ledger (job_id);

CREATE TABLE IF NOT EXISTS rate_limits (
    key VARCHAR(255) PRIMARY KEY,
    count INTEGER NOT NULL DEFAULT 1,
    window_start BIGINT NOT NULL,
    expires_at BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_rate_limits_expires_at ON rate_limits (expires_at);

INSERT INTO ai_models (id, input_price_per_1m, output_price_per_1m, currency, active, updated_at)
VALUES
    ('gpt-4o', 5.00, 15.00, 'USD', TRUE, 1734560000),
    ('gpt-4o-mini', 0.15, 0.60, 'USD', TRUE, 1734560000),
    ('gpt-5-mini', 0.25, 2.00, 'USD', TRUE, 1734560000)
ON CONFLICT (id) DO NOTHING;
